In [2]:
import numpy as np

In [24]:
class NeuralNetwork():
    def __init (self):
        #seeding for random number generation
        np.random.seed(1)
        
        #converting weights to a 3 by 1 matrix w values -1 to 1 and mean of 0
        self.synaptic_weights = 2*np.random.random((3,1)) - 1
    def sigmoid(self, x):
    #applying the sigmoid function
      return 1 / ( 1 + np.exp( -x ) )

    def sigmoid_derivative(self, x):
    #computing derivative to the sigmoid function
      return x * ( 1 - x )

    def train( self , training_inputs , training_outputs , training_iterations ):
    #training the model to make accurate predictions while adjusting weights continually
      for iteration in range(training_iterations):
        #siphon the training data via the neuron
        output = self.think(training_inputs)
        
        #computing error rate for backpropogation
        error = training_outputs - output
        
        #performing weight adjustments
        adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))
        
        self.synpatic_weights += adjustments
        
    def think(self, inputs):
    #passing the inputs via the neuron to get output
    #converting values to float
    
     return output

In [28]:
neural_network = NeuralNetwork()
    
print( " Beginninh Randomly Generatedn Weights: " )
    
print( neural_network.synaptic_weights )
    
training_inputs = np.array( [ [ 0 , 0 , 1 ] , [ 1 , 1 , 1 ] , [ 1 , 0 , 1 ] , [ 0 , 1 , 1 ]] )
    
training_outputs = np.array( [ [ 0 , 1 , 1 , 0 ] ] ) . T
    
neural_network.train( training_inputs , training_outputs , 15000 )
    
print( " Ending Weights After Training: " )
print(neural_network.synaptic_weights)

user_input_one = str(input( " User Input One: " ))
user_input_two = str(input( " User Input Two: " ))
user_input_three = str(input( " User Input Three: " ))
    
print( " Considering New Situations: " , user_input_one , user_input_two , user_input_three )
print( " New Output Data: " )
print( neural_network.think ( np.array ( [ user_input_one , user_input_two , user_input_three ] ) ) )
    
print( " ENJOY YOUR DAY!!!!!!! " )

 Beginninh Randomly Generatedn Weights: 
0
 Ending Weights After Training: 
[[10.08729888 10.08729888 10.08729888]
 [-0.20733391 -0.20733391 -0.20733391]
 [-4.83729645 -4.83729645 -4.83729645]]
 User Input One: 1
 User Input Two: 0
 User Input Three: 0
 Considering New Situations:  1 0 0
 New Output Data: 
[0.9999584 0.9999584 0.9999584]
 ENJOY YOUR DAY!!!!!!! 
